# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
